// Banco de casos do jogo de interpretação de testes respiratórios (H₂/CH₄),
// portado do app do Rafael (nuvem-ensino-game.vercel.app) para o curso
// "Aperfeiçoamento em Teste Respiratório Hidrogênio e Metano".
//
// A versão em espanhol do site original usa um algoritmo de troca de palavras
// por regex que nunca chega a ser fiel (e nem dispara de fato, por um bug de
// escopo no app original) — aqui os 30 casos foram traduzidos à mão.

export type MarkerKind = "time" | "threshold" | "delta" | "point" | "flat";

export type CaseMarker = {
  kind: MarkerKind;
  time?: number;
  gas?: "h2" | "ch4";
  value?: number;
  base?: number;
};

export type RespiratoryCase = {
  id: string;
  difficulty: 1 | 2 | 3 | 4;
  category: "SIBO" | "IMO" | "Lactose" | "Frutose" | "Sacarose" | "Qualidade";
  type: string;
  claim: string;
  answer: boolean;
  t: number[];
  h2: number[];
  ch4: number[];
  meta: [string, string, string];
  short: string;
  why: string;
  detail: string;
  marker: CaseMarker;
};

export const respiratoryCasesPt: RespiratoryCase[] = [
  { id: "sibo-b1", difficulty: 1, category: "SIBO", type: "SIBO • H₂", claim: "O gráfico é compatível com SIBO positivo.", answer: true, t: [0, 15, 30, 45, 60, 75, 90, 120], h2: [4, 7, 11, 18, 27, 34, 39, 58], ch4: [2, 2, 3, 3, 4, 4, 4, 5], meta: ["Lactulose", "Basal H₂: 4 ppm", "Sem sintomas"], short: "H₂: +35 ppm até 90 min", why: "Até 90 minutos, o H₂ sobe 35 ppm acima do basal. O critério treinado é elevação >20 ppm acima do basal até 90 min.", detail: "O ponto decisivo é a janela de 90 minutos. A elevação tardia aos 120 min pode representar fermentação colônica.", marker: { kind: "time", time: 90 } },
  { id: "sibo-b2", difficulty: 1, category: "SIBO", type: "SIBO • H₂", claim: "A elevação somente aos 120 minutos torna o teste positivo para SIBO.", answer: false, t: [0, 15, 30, 45, 60, 75, 90, 120], h2: [3, 4, 5, 6, 7, 8, 9, 34], ch4: [2, 2, 2, 2, 3, 3, 3, 4], meta: ["Lactulose", "Basal H₂: 3 ppm", "Elevação tardia"], short: "Elevação somente aos 120 min", why: "Não há aumento >20 ppm acima do basal até 90 minutos. A elevação aparece apenas aos 120 min.", detail: "O erro clássico é olhar apenas o pico final. Para SIBO, o tempo em que a elevação acontece é parte essencial do critério.", marker: { kind: "time", time: 90 } },
  { id: "imo-b1", difficulty: 1, category: "IMO", type: "IMO • CH₄", claim: "O gráfico é compatível com IMO positivo.", answer: true, t: [0, 15, 30, 45, 60, 75, 90, 120], h2: [3, 4, 4, 5, 5, 6, 7, 8], ch4: [11, 13, 17, 20, 24, 28, 25, 22], meta: ["Lactulose", "Basal CH₄: 11 ppm", "Dor + distensão"], short: "CH₄ basal: 11 ppm", why: "O CH₄ já está ≥10 ppm na leitura basal. Pelo material, CH₄ ≥10 ppm em qualquer momento sustenta IMO positivo.", detail: "O valor absoluto de CH₄ é o ponto decisivo neste caso.", marker: { kind: "threshold", gas: "ch4", value: 10 } },
  { id: "imo-b2", difficulty: 1, category: "IMO", type: "IMO • CH₄", claim: "CH₄ máximo de 7 ppm preenche o critério de IMO.", answer: false, t: [0, 15, 30, 45, 60, 75, 90, 120], h2: [2, 3, 4, 4, 5, 6, 7, 8], ch4: [2, 3, 3, 4, 4, 5, 6, 7], meta: ["Glicose", "Maior CH₄: 7 ppm", "Sem sintomas"], short: "CH₄ máximo: 7 ppm", why: "O CH₄ permanece abaixo de 10 ppm durante todo o teste.", detail: "Para IMO, o critério treinado usa o valor absoluto de CH₄.", marker: { kind: "threshold", gas: "ch4", value: 10 } },
  { id: "lac-b1", difficulty: 1, category: "Lactose", type: "Lactose • H₂", claim: "A curva com elevação de H₂ e sintomas é compatível com intolerância à lactose.", answer: true, t: [0, 30, 60, 90, 120, 150, 180], h2: [5, 7, 9, 12, 28, 64, 92], ch4: [2, 2, 3, 3, 4, 4, 5], meta: ["Lactose", "Basal H₂: 5 ppm", "Diarreia + flatulência"], short: "Elevação de H₂ + sintomas", why: "Há elevação ≥20 ppm acima do basal e sintomas gastrointestinais.", detail: "Sem sintomas, a mesma elevação seria classificada como má absorção.", marker: { kind: "delta", gas: "h2", base: 5, value: 25 } },
  { id: "fru-b1", difficulty: 1, category: "Frutose", type: "Frutose • H₂", claim: "Elevação de H₂ sem sintomas basta para chamar o teste de intolerância à frutose.", answer: false, t: [0, 30, 60, 90, 120, 150, 180], h2: [5, 7, 8, 11, 25, 27, 26], ch4: [2, 2, 2, 3, 3, 3, 4], meta: ["Frutose", "Basal H₂: 5 ppm", "Sem sintomas"], short: "H₂ +20 ppm, sem sintomas", why: "A elevação sem sintomas corresponde a má absorção, não intolerância clínica.", detail: "O material diferencia má absorção de intolerância pela presença de sintomas.", marker: { kind: "delta", gas: "h2", base: 5, value: 25 } },
  { id: "sac-b1", difficulty: 1, category: "Sacarose", type: "Sacarose • H₂", claim: "Uma elevação ≥20 ppm acima do basal, sem sintomas, é compatível com má absorção à sacarose.", answer: true, t: [0, 30, 60, 90, 120, 150, 180], h2: [4, 6, 9, 14, 25, 31, 34], ch4: [2, 2, 2, 3, 3, 3, 4], meta: ["Sacarose", "Basal H₂: 4 ppm", "Sem sintomas"], short: "H₂ +30 ppm sem sintomas", why: "A curva supera 20 ppm acima do basal e não há sintomas.", detail: "No material, essa combinação é classificada como má absorção à sacarose.", marker: { kind: "delta", gas: "h2", base: 4, value: 24 } },
  { id: "qual-b1", difficulty: 1, category: "Qualidade", type: "Qualidade do exame", claim: "Basal de H₂ em 40 ppm permite interpretar o exame normalmente.", answer: false, t: [0, 15, 30, 45, 60, 75, 90, 120], h2: [40, 34, 29, 23, 18, 14, 11, 30], ch4: [3, 3, 3, 3, 4, 4, 4, 5], meta: ["Teste H₂", "Basal H₂: 40 ppm", "Preparo duvidoso"], short: "Basal H₂ muito elevado", why: "O basal está muito elevado e exige avaliação do preparo e repetição da leitura.", detail: "A qualidade vem antes do diagnóstico. O material orienta checar jejum/dieta e repetir a leitura.", marker: { kind: "point", gas: "h2", time: 0 } },
  { id: "sibo-i1", difficulty: 2, category: "SIBO", type: "SIBO • H₂", claim: "Com basal de 8 ppm e H₂ de 31 ppm aos 75 min, o teste é compatível com SIBO positivo.", answer: true, t: [0, 15, 30, 45, 60, 75, 90, 120], h2: [8, 10, 13, 17, 22, 31, 35, 52], ch4: [2, 2, 3, 3, 3, 4, 4, 5], meta: ["Glicose", "Basal H₂: 8 ppm", "Sem diarreia"], short: "+23 ppm aos 75 min", why: "A elevação acima do basal supera 20 ppm antes de 90 minutos.", detail: "Sintomas não são obrigatórios para o critério de positividade de SIBO descrito no material.", marker: { kind: "time", time: 75 } },
  { id: "sibo-i2", difficulty: 2, category: "SIBO", type: "SIBO • H₂", claim: "Com basal de 7 ppm e pico de 26 ppm aos 90 min, o teste é positivo para SIBO.", answer: false, t: [0, 15, 30, 45, 60, 75, 90, 120], h2: [7, 8, 10, 13, 17, 21, 26, 45], ch4: [2, 2, 2, 3, 3, 3, 4, 5], meta: ["Lactulose", "Basal H₂: 7 ppm", "Pico 26 ppm aos 90 min"], short: "Aumento de apenas 19 ppm", why: "26 ppm representa aumento de 19 ppm em relação ao basal de 7 ppm.", detail: "O caso treina a necessidade de calcular a variação em relação ao basal, não usar o valor absoluto do pico.", marker: { kind: "delta", gas: "h2", base: 7, value: 27 } },
  { id: "imo-i1", difficulty: 2, category: "IMO", type: "IMO • CH₄", claim: "CH₄ de 10 ppm aos 60 minutos já satisfaz o critério de IMO.", answer: true, t: [0, 15, 30, 45, 60, 75, 90, 120], h2: [4, 5, 6, 7, 8, 9, 10, 11], ch4: [4, 5, 6, 8, 10, 12, 13, 14], meta: ["Lactulose", "CH₄ = 10 ppm aos 60 min", "Sem sintomas"], short: "CH₄ atinge 10 ppm", why: "O valor de CH₄ atinge o ponto de corte de 10 ppm.", detail: "O critério treinado aceita ≥10 ppm em qualquer momento.", marker: { kind: "threshold", gas: "ch4", value: 10 } },
  { id: "imo-i2", difficulty: 2, category: "IMO", type: "IMO • CH₄", claim: "A ausência de sintomas exclui IMO mesmo quando o CH₄ chega a 18 ppm.", answer: false, t: [0, 15, 30, 45, 60, 75, 90, 120], h2: [3, 4, 4, 5, 6, 6, 7, 8], ch4: [5, 7, 9, 12, 16, 18, 17, 16], meta: ["Glicose", "CH₄ máximo: 18 ppm", "Sem sintomas"], short: "CH₄ ≥10 ppm apesar de assintomático", why: "Sintomas não são necessários para o critério apresentado de IMO.", detail: "O valor gasométrico é suficiente para a classificação treinada.", marker: { kind: "threshold", gas: "ch4", value: 10 } },
  { id: "lac-i1", difficulty: 2, category: "Lactose", type: "Lactose • H₂", claim: "A curva é compatível com má absorção à lactose, mas não necessariamente intolerância.", answer: true, t: [0, 30, 60, 90, 120, 150, 180], h2: [3, 5, 8, 13, 26, 34, 39], ch4: [2, 2, 2, 3, 3, 4, 4], meta: ["Lactose", "Basal H₂: 3 ppm", "Sem sintomas"], short: "Elevação sem sintomas", why: "A elevação supera 20 ppm acima do basal, mas não há sintomas.", detail: "O material diferencia má absorção de intolerância justamente pela presença de sintomas.", marker: { kind: "delta", gas: "h2", base: 3, value: 23 } },
  { id: "fru-i1", difficulty: 2, category: "Frutose", type: "Frutose • H₂", claim: "Com sintomas e aumento de 22 ppm acima do basal, o teste é compatível com intolerância à frutose.", answer: true, t: [0, 30, 60, 90, 120, 150, 180], h2: [4, 6, 8, 12, 26, 29, 31], ch4: [2, 2, 2, 3, 3, 3, 4], meta: ["Frutose", "Basal H₂: 4 ppm", "Dor + distensão"], short: "+22 ppm + sintomas", why: "A curva supera 20 ppm acima do basal e há sintomas.", detail: "Essa associação é classificada como intolerância à frutose no material.", marker: { kind: "delta", gas: "h2", base: 4, value: 24 } },
  { id: "sac-i1", difficulty: 2, category: "Sacarose", type: "Sacarose • H₂", claim: "Basal de 9 ppm e pico de 28 ppm não alcançam o critério de má absorção à sacarose.", answer: true, t: [0, 30, 60, 90, 120, 150, 180], h2: [9, 10, 12, 15, 21, 26, 28], ch4: [2, 2, 2, 3, 3, 3, 4], meta: ["Sacarose", "Basal H₂: 9 ppm", "Sem sintomas"], short: "Aumento máximo de 19 ppm", why: "O aumento máximo é de 19 ppm em relação ao basal.", detail: "O caso treina cálculo relativo ao basal.", marker: { kind: "delta", gas: "h2", base: 9, value: 29 } },
  { id: "qual-i1", difficulty: 2, category: "Qualidade", type: "Qualidade do exame", claim: "Uma queda abrupta isolada aos 75 min deve motivar repetição da leitura.", answer: true, t: [0, 15, 30, 45, 60, 75, 90, 120], h2: [4, 7, 12, 20, 38, 10, 47, 71], ch4: [2, 2, 2, 3, 3, 3, 4, 4], meta: ["SIBO • H₂", "Queda isolada: 75 min", "Suspeita de sopro fraco"], short: "Queda isolada aos 75 min", why: "O material descreve esse padrão como provável erro de leitura ou sopro fraco.", detail: "A recomendação é repetir a leitura, de preferência com outro aparelho, e checar a qualidade do sopro.", marker: { kind: "point", gas: "h2", time: 75 } },
  { id: "sibo-a1", difficulty: 3, category: "SIBO", type: "SIBO • H₂", claim: "H₂ baixo durante todo o exame exclui completamente SIBO e encerra a investigação.", answer: false, t: [0, 15, 30, 45, 60, 75, 90, 120], h2: [1, 1, 2, 1, 2, 2, 1, 2], ch4: [2, 2, 2, 2, 3, 3, 3, 4], meta: ["Lactulose", "H₂ persistentemente baixo", "Sem elevação colônica"], short: "Possível não respondedor ao H₂", why: "O material descreve não respondedores de H₂ e orienta realizar teste com CH₄.", detail: "Curva plana não deve ser interpretada automaticamente como exclusão definitiva quando há suspeita de não produção de H₂.", marker: { kind: "flat", gas: "h2" } },
  { id: "sibo-a2", difficulty: 3, category: "SIBO", type: "SIBO • H₂", claim: "Um pico aos 120 min pode ser usado como evidência principal de SIBO quando não houve elevação antes de 90 min.", answer: false, t: [0, 15, 30, 45, 60, 75, 90, 120], h2: [5, 6, 7, 8, 10, 12, 13, 46], ch4: [2, 2, 2, 2, 3, 3, 3, 4], meta: ["Lactulose", "Pico tardio: 120 min", "Sem sintomas"], short: "Pico tardio fora da janela", why: "A elevação apenas aos 120 min pode refletir fermentação colônica.", detail: "A janela temporal é parte do critério e evita confundir fermentação colônica com SIBO.", marker: { kind: "time", time: 90 } },
  { id: "imo-a1", difficulty: 3, category: "IMO", type: "IMO • CH₄", claim: "H₂ baixo com CH₄ de 33 ppm aos 120 min pode indicar IMO mesmo com SIBO negativo.", answer: true, t: [0, 15, 30, 45, 60, 75, 90, 120], h2: [2, 3, 3, 4, 4, 5, 5, 6], ch4: [4, 6, 8, 11, 16, 22, 28, 33], meta: ["Lactulose", "CH₄: 33 ppm aos 120 min", "Distensão sem diarreia"], short: "CH₄ elevado com H₂ baixo", why: "O material apresenta exatamente esse padrão: SIBO negativo por H₂ e IMO positivo por CH₄.", detail: "A leitura conjunta dos gases evita perder o diagnóstico de IMO em pacientes com H₂ baixo.", marker: { kind: "threshold", gas: "ch4", value: 10 } },
  { id: "lac-a1", difficulty: 3, category: "Lactose", type: "Lactose • H₂", claim: "Diarreia e flatulência intensas, com H₂ sem elevação, confirmam intolerância à lactose.", answer: false, t: [0, 30, 60, 90, 120, 150, 180], h2: [1, 2, 2, 3, 4, 5, 6], ch4: [2, 2, 2, 2, 3, 3, 3], meta: ["Lactose", "H₂ sem elevação", "Diarreia + flatulência"], short: "Sintomas sem critério gasométrico", why: "Sintomas isolados não confirmam intolerância pelo teste; o material considera não respondedor e repetição com CH₄.", detail: "É um cenário de possível falso negativo do H₂.", marker: { kind: "flat", gas: "h2" } },
  { id: "fru-a1", difficulty: 3, category: "Frutose", type: "Frutose • H₂", claim: "Um teste de frutose deve ser interpretado até 180 minutos, e não encerrado aos 90 minutos.", answer: true, t: [0, 30, 60, 90, 120, 150, 180], h2: [3, 4, 6, 8, 15, 26, 34], ch4: [2, 2, 2, 2, 3, 3, 4], meta: ["Frutose", "Elevação após 120 min", "Sem sintomas"], short: "Monitorização até 180 min", why: "O material descreve leituras de 30 em 30 minutos até 180 minutos para frutose.", detail: "Encerrar aos 90 min pode perder elevações relevantes para testes de carboidratos.", marker: { kind: "time", time: 180 } },
  { id: "sac-a1", difficulty: 3, category: "Sacarose", type: "Sacarose • H₂", claim: "Se a primeira leitura basal estiver registrada incorretamente, o limiar do gráfico também ficará incorreto.", answer: true, t: [0, 30, 60, 90, 120, 150, 180], h2: [10, 12, 15, 22, 31, 38, 42], ch4: [2, 2, 2, 3, 3, 3, 4], meta: ["Sacarose", "Basal: 10 ppm", "Sem sintomas"], short: "Basal define o limiar", why: "O material mostra um exemplo de erro gráfico causado por posicionar incorretamente a primeira leitura.", detail: "A interpretação depende da variação em relação ao basal.", marker: { kind: "point", gas: "h2", time: 0 } },
  { id: "qual-a1", difficulty: 3, category: "Qualidade", type: "Qualidade do exame", claim: "Leituras persistentemente zeradas podem representar não respondedor ao H₂ ou problema de calibração.", answer: true, t: [0, 15, 30, 45, 60, 75, 90, 120], h2: [0, 0, 0, 0, 0, 0, 0, 0], ch4: [2, 2, 2, 2, 2, 2, 2, 2], meta: ["Teste H₂", "Todas as leituras: 0", "Checar aparelho/paciente"], short: "Curva totalmente zerada", why: "O material cita erro de calibração ou não respondedor ao H₂ como possibilidades.", detail: "A orientação é avaliar equipamento e, no contexto de não respondedor, considerar teste H₂–CH₄.", marker: { kind: "flat", gas: "h2" } },
  { id: "qual-e1", difficulty: 4, category: "Qualidade", type: "Qualidade do exame", claim: "Vômito durante o exame pode justificar suspensão e remarcação por risco de falso negativo.", answer: true, t: [0, 15, 30, 45, 60, 75, 90, 120], h2: [4, 5, 7, 9, 10, 11, 12, 13], ch4: [2, 2, 2, 3, 3, 3, 4, 4], meta: ["Monitorização", "Vômito após substrato", "Risco de perda do substrato"], short: "Vômito compromete o exame", why: "O material orienta suspender e remarcar porque o substrato pode ter sido eliminado, levando a falso negativo.", detail: "Aqui o ponto central não é a curva, mas a validade pré-analítica da monitorização.", marker: { kind: "time", time: 45 } },
  { id: "qual-e2", difficulty: 4, category: "Qualidade", type: "Qualidade do exame", claim: "Tabagismo durante o estudo pode elevar H₂ e gerar falso positivo.", answer: true, t: [0, 15, 30, 45, 60, 75, 90, 120], h2: [4, 5, 7, 18, 30, 38, 42, 48], ch4: [2, 2, 2, 3, 3, 4, 4, 5], meta: ["Qualidade", "Paciente fumou durante o teste", "Fator de confusão"], short: "Tabagismo altera H₂", why: "O material cita o fumo como causa de falso positivo e alteração das concentrações de H₂.", detail: "O caso treina reconhecimento de interferente antes de interpretar o gráfico.", marker: { kind: "time", time: 45 } },
  { id: "qual-e3", difficulty: 4, category: "Qualidade", type: "Qualidade do exame", claim: "Dormir durante o teste pode aumentar H₂ por hipoventilação e produzir falso positivo.", answer: true, t: [0, 15, 30, 45, 60, 75, 90, 120], h2: [5, 6, 8, 12, 25, 31, 35, 39], ch4: [2, 2, 2, 3, 3, 3, 4, 4], meta: ["Qualidade", "Paciente dormiu", "Hipoventilação"], short: "Sono durante o exame", why: "O material inclui dormir durante o exame como causa possível de falso positivo por hipoventilação.", detail: "O treinamento deve separar padrão gasométrico de interferência técnica/comportamental.", marker: { kind: "time", time: 60 } },
  { id: "qual-e4", difficulty: 4, category: "Qualidade", type: "Qualidade do exame", claim: "Sopro curto ou fraco pode contribuir para falso negativo em idosos, asmáticos e crianças.", answer: true, t: [0, 15, 30, 45, 60, 75, 90, 120], h2: [3, 3, 4, 4, 5, 5, 6, 6], ch4: [2, 2, 2, 2, 3, 3, 3, 3], meta: ["Qualidade", "Sopro curto/fraco", "Paciente idoso"], short: "Coleta expiratória inadequada", why: "O material relaciona sopro incorreto a falsos negativos, especialmente em idosos, asmáticos e crianças.", detail: "Antes de concluir negatividade, a qualidade da coleta deve ser verificada.", marker: { kind: "flat", gas: "h2" } },
  { id: "sibo-e1", difficulty: 4, category: "SIBO", type: "SIBO • H₂", claim: "Em um caso com SIBO previamente positivo, teste de intolerância à frutose deve ser interpretado com cautela por risco de falso positivo.", answer: true, t: [0, 30, 60, 90, 120, 150, 180], h2: [5, 12, 24, 36, 48, 55, 60], ch4: [2, 2, 3, 3, 4, 4, 5], meta: ["Frutose após SIBO positivo", "Curva precoce", "Risco de falso positivo"], short: "SIBO pode confundir teste de CHO", why: "O material orienta realizar SIBO primeiro, pois SIBO positivo pode gerar falsos positivos em testes de intolerância.", detail: "Esse é um caso de integração entre sequência diagnóstica e interpretação do gráfico.", marker: { kind: "time", time: 90 } },
  { id: "lac-e1", difficulty: 4, category: "Lactose", type: "Lactose • H₂/CH₄", claim: "H₂ e CH₄ baixos até 180 minutos, apesar de diarreia, ainda não comprovam intolerância à lactose.", answer: true, t: [0, 30, 60, 90, 120, 150, 180], h2: [3, 4, 5, 5, 6, 7, 7], ch4: [2, 2, 3, 3, 4, 4, 4], meta: ["Lactose", "H₂/CH₄ sem elevação", "Diarreia"], short: "Sintomas sem elevação em ambos os gases", why: "O material apresenta cenário semelhante e discute a possibilidade de outro perfil, sem confirmar intolerância pelo teste.", detail: "O ensino aqui é resistir à tentação de transformar sintoma isolado em resultado positivo.", marker: { kind: "flat", gas: "h2" } },
  { id: "fru-e1", difficulty: 4, category: "Frutose", type: "Frutose • H₂", claim: "Em teste de frutose, sintomas devem ser considerados na classificação entre má absorção e intolerância.", answer: true, t: [0, 30, 60, 90, 120, 150, 180], h2: [4, 6, 9, 13, 27, 35, 38], ch4: [2, 2, 2, 3, 3, 3, 4], meta: ["Frutose", "H₂ +34 ppm", "Dor + distensão"], short: "Curva positiva + sintomas", why: "O material incorporou a presença de sintomas na classificação de intolerância a carboidratos.", detail: "O gráfico define má absorção; a associação com sintomas sustenta a classificação de intolerância no material.", marker: { kind: "delta", gas: "h2", base: 4, value: 24 } },
];

export const respiratoryCasesEs: RespiratoryCase[] = [
  { id: "sibo-b1", difficulty: 1, category: "SIBO", type: "SIBO • H₂", claim: "El gráfico es compatible con SIBO positivo.", answer: true, t: [0, 15, 30, 45, 60, 75, 90, 120], h2: [4, 7, 11, 18, 27, 34, 39, 58], ch4: [2, 2, 3, 3, 4, 4, 4, 5], meta: ["Lactulosa", "Basal H₂: 4 ppm", "Sin síntomas"], short: "H₂: +35 ppm hasta los 90 min", why: "Hasta los 90 minutos, el H₂ sube 35 ppm por encima del basal. El criterio entrenado es una elevación >20 ppm por encima del basal hasta los 90 min.", detail: "El punto decisivo es la ventana de 90 minutos. La elevación tardía a los 120 min puede representar fermentación colónica.", marker: { kind: "time", time: 90 } },
  { id: "sibo-b2", difficulty: 1, category: "SIBO", type: "SIBO • H₂", claim: "La elevación solo a los 120 minutos hace que la prueba sea positiva para SIBO.", answer: false, t: [0, 15, 30, 45, 60, 75, 90, 120], h2: [3, 4, 5, 6, 7, 8, 9, 34], ch4: [2, 2, 2, 2, 3, 3, 3, 4], meta: ["Lactulosa", "Basal H₂: 3 ppm", "Elevación tardía"], short: "Elevación solo a los 120 min", why: "No hay un aumento >20 ppm por encima del basal hasta los 90 minutos. La elevación aparece solo a los 120 min.", detail: "El error clásico es mirar solo el pico final. Para SIBO, el momento en que ocurre la elevación es parte esencial del criterio.", marker: { kind: "time", time: 90 } },
  { id: "imo-b1", difficulty: 1, category: "IMO", type: "IMO • CH₄", claim: "El gráfico es compatible con IMO positivo.", answer: true, t: [0, 15, 30, 45, 60, 75, 90, 120], h2: [3, 4, 4, 5, 5, 6, 7, 8], ch4: [11, 13, 17, 20, 24, 28, 25, 22], meta: ["Lactulosa", "Basal CH₄: 11 ppm", "Dolor + distensión"], short: "CH₄ basal: 11 ppm", why: "El CH₄ ya está ≥10 ppm en la lectura basal. Según el material, CH₄ ≥10 ppm en cualquier momento sustenta un IMO positivo.", detail: "El valor absoluto de CH₄ es el punto decisivo en este caso.", marker: { kind: "threshold", gas: "ch4", value: 10 } },
  { id: "imo-b2", difficulty: 1, category: "IMO", type: "IMO • CH₄", claim: "Un CH₄ máximo de 7 ppm cumple el criterio de IMO.", answer: false, t: [0, 15, 30, 45, 60, 75, 90, 120], h2: [2, 3, 4, 4, 5, 6, 7, 8], ch4: [2, 3, 3, 4, 4, 5, 6, 7], meta: ["Glucosa", "CH₄ máximo: 7 ppm", "Sin síntomas"], short: "CH₄ máximo: 7 ppm", why: "El CH₄ permanece por debajo de 10 ppm durante toda la prueba.", detail: "Para IMO, el criterio entrenado usa el valor absoluto de CH₄.", marker: { kind: "threshold", gas: "ch4", value: 10 } },
  { id: "lac-b1", difficulty: 1, category: "Lactose", type: "Lactosa • H₂", claim: "La curva con elevación de H₂ y síntomas es compatible con intolerancia a la lactosa.", answer: true, t: [0, 30, 60, 90, 120, 150, 180], h2: [5, 7, 9, 12, 28, 64, 92], ch4: [2, 2, 3, 3, 4, 4, 5], meta: ["Lactosa", "Basal H₂: 5 ppm", "Diarrea + flatulencia"], short: "Elevación de H₂ + síntomas", why: "Hay una elevación ≥20 ppm por encima del basal y síntomas gastrointestinales.", detail: "Sin síntomas, la misma elevación se clasificaría como malabsorción.", marker: { kind: "delta", gas: "h2", base: 5, value: 25 } },
  { id: "fru-b1", difficulty: 1, category: "Frutose", type: "Fructosa • H₂", claim: "Una elevación de H₂ sin síntomas basta para llamar a la prueba intolerancia a la fructosa.", answer: false, t: [0, 30, 60, 90, 120, 150, 180], h2: [5, 7, 8, 11, 25, 27, 26], ch4: [2, 2, 2, 3, 3, 3, 4], meta: ["Fructosa", "Basal H₂: 5 ppm", "Sin síntomas"], short: "H₂ +20 ppm, sin síntomas", why: "La elevación sin síntomas corresponde a malabsorción, no a intolerancia clínica.", detail: "El material diferencia malabsorción de intolerancia por la presencia de síntomas.", marker: { kind: "delta", gas: "h2", base: 5, value: 25 } },
  { id: "sac-b1", difficulty: 1, category: "Sacarose", type: "Sacarosa • H₂", claim: "Una elevación ≥20 ppm por encima del basal, sin síntomas, es compatible con malabsorción a la sacarosa.", answer: true, t: [0, 30, 60, 90, 120, 150, 180], h2: [4, 6, 9, 14, 25, 31, 34], ch4: [2, 2, 2, 3, 3, 3, 4], meta: ["Sacarosa", "Basal H₂: 4 ppm", "Sin síntomas"], short: "H₂ +30 ppm sin síntomas", why: "La curva supera 20 ppm por encima del basal y no hay síntomas.", detail: "En el material, esta combinación se clasifica como malabsorción a la sacarosa.", marker: { kind: "delta", gas: "h2", base: 4, value: 24 } },
  { id: "qual-b1", difficulty: 1, category: "Qualidade", type: "Calidad del examen", claim: "Un basal de H₂ de 40 ppm permite interpretar el examen normalmente.", answer: false, t: [0, 15, 30, 45, 60, 75, 90, 120], h2: [40, 34, 29, 23, 18, 14, 11, 30], ch4: [3, 3, 3, 3, 4, 4, 4, 5], meta: ["Prueba de H₂", "Basal H₂: 40 ppm", "Preparación dudosa"], short: "Basal H₂ muy elevado", why: "El basal está muy elevado y exige evaluar la preparación y repetir la lectura.", detail: "La calidad viene antes del diagnóstico. El material orienta a revisar el ayuno/dieta y repetir la lectura.", marker: { kind: "point", gas: "h2", time: 0 } },
  { id: "sibo-i1", difficulty: 2, category: "SIBO", type: "SIBO • H₂", claim: "Con un basal de 8 ppm y H₂ de 31 ppm a los 75 min, la prueba es compatible con SIBO positivo.", answer: true, t: [0, 15, 30, 45, 60, 75, 90, 120], h2: [8, 10, 13, 17, 22, 31, 35, 52], ch4: [2, 2, 3, 3, 3, 4, 4, 5], meta: ["Glucosa", "Basal H₂: 8 ppm", "Sin diarrea"], short: "+23 ppm a los 75 min", why: "La elevación por encima del basal supera 20 ppm antes de los 90 minutos.", detail: "Los síntomas no son obligatorios para el criterio de positividad de SIBO descrito en el material.", marker: { kind: "time", time: 75 } },
  { id: "sibo-i2", difficulty: 2, category: "SIBO", type: "SIBO • H₂", claim: "Con un basal de 7 ppm y un pico de 26 ppm a los 90 min, la prueba es positiva para SIBO.", answer: false, t: [0, 15, 30, 45, 60, 75, 90, 120], h2: [7, 8, 10, 13, 17, 21, 26, 45], ch4: [2, 2, 2, 3, 3, 3, 4, 5], meta: ["Lactulosa", "Basal H₂: 7 ppm", "Pico 26 ppm a los 90 min"], short: "Aumento de solo 19 ppm", why: "26 ppm representa un aumento de 19 ppm en relación con el basal de 7 ppm.", detail: "El caso entrena la necesidad de calcular la variación respecto al basal, sin usar el valor absoluto del pico.", marker: { kind: "delta", gas: "h2", base: 7, value: 27 } },
  { id: "imo-i1", difficulty: 2, category: "IMO", type: "IMO • CH₄", claim: "Un CH₄ de 10 ppm a los 60 minutos ya satisface el criterio de IMO.", answer: true, t: [0, 15, 30, 45, 60, 75, 90, 120], h2: [4, 5, 6, 7, 8, 9, 10, 11], ch4: [4, 5, 6, 8, 10, 12, 13, 14], meta: ["Lactulosa", "CH₄ = 10 ppm a los 60 min", "Sin síntomas"], short: "CH₄ alcanza 10 ppm", why: "El valor de CH₄ alcanza el punto de corte de 10 ppm.", detail: "El criterio entrenado acepta ≥10 ppm en cualquier momento.", marker: { kind: "threshold", gas: "ch4", value: 10 } },
  { id: "imo-i2", difficulty: 2, category: "IMO", type: "IMO • CH₄", claim: "La ausencia de síntomas excluye IMO incluso cuando el CH₄ llega a 18 ppm.", answer: false, t: [0, 15, 30, 45, 60, 75, 90, 120], h2: [3, 4, 4, 5, 6, 6, 7, 8], ch4: [5, 7, 9, 12, 16, 18, 17, 16], meta: ["Glucosa", "CH₄ máximo: 18 ppm", "Sin síntomas"], short: "CH₄ ≥10 ppm a pesar de estar asintomático", why: "Los síntomas no son necesarios para el criterio presentado de IMO.", detail: "El valor gasométrico es suficiente para la clasificación entrenada.", marker: { kind: "threshold", gas: "ch4", value: 10 } },
  { id: "lac-i1", difficulty: 2, category: "Lactose", type: "Lactosa • H₂", claim: "La curva es compatible con malabsorción a la lactosa, pero no necesariamente con intolerancia.", answer: true, t: [0, 30, 60, 90, 120, 150, 180], h2: [3, 5, 8, 13, 26, 34, 39], ch4: [2, 2, 2, 3, 3, 4, 4], meta: ["Lactosa", "Basal H₂: 3 ppm", "Sin síntomas"], short: "Elevación sin síntomas", why: "La elevación supera 20 ppm por encima del basal, pero no hay síntomas.", detail: "El material diferencia malabsorción de intolerancia justamente por la presencia de síntomas.", marker: { kind: "delta", gas: "h2", base: 3, value: 23 } },
  { id: "fru-i1", difficulty: 2, category: "Frutose", type: "Fructosa • H₂", claim: "Con síntomas y un aumento de 22 ppm por encima del basal, la prueba es compatible con intolerancia a la fructosa.", answer: true, t: [0, 30, 60, 90, 120, 150, 180], h2: [4, 6, 8, 12, 26, 29, 31], ch4: [2, 2, 2, 3, 3, 3, 4], meta: ["Fructosa", "Basal H₂: 4 ppm", "Dolor + distensión"], short: "+22 ppm + síntomas", why: "La curva supera 20 ppm por encima del basal y hay síntomas.", detail: "Esta asociación se clasifica como intolerancia a la fructosa en el material.", marker: { kind: "delta", gas: "h2", base: 4, value: 24 } },
  { id: "sac-i1", difficulty: 2, category: "Sacarose", type: "Sacarosa • H₂", claim: "Un basal de 9 ppm y un pico de 28 ppm no alcanzan el criterio de malabsorción a la sacarosa.", answer: true, t: [0, 30, 60, 90, 120, 150, 180], h2: [9, 10, 12, 15, 21, 26, 28], ch4: [2, 2, 2, 3, 3, 3, 4], meta: ["Sacarosa", "Basal H₂: 9 ppm", "Sin síntomas"], short: "Aumento máximo de 19 ppm", why: "El aumento máximo es de 19 ppm en relación con el basal.", detail: "El caso entrena el cálculo relativo al basal.", marker: { kind: "delta", gas: "h2", base: 9, value: 29 } },
  { id: "qual-i1", difficulty: 2, category: "Qualidade", type: "Calidad del examen", claim: "Una caída abrupta aislada a los 75 min debe motivar la repetición de la lectura.", answer: true, t: [0, 15, 30, 45, 60, 75, 90, 120], h2: [4, 7, 12, 20, 38, 10, 47, 71], ch4: [2, 2, 2, 3, 3, 3, 4, 4], meta: ["SIBO • H₂", "Caída aislada: 75 min", "Sospecha de soplo débil"], short: "Caída aislada a los 75 min", why: "El material describe este patrón como probable error de lectura o soplo débil.", detail: "La recomendación es repetir la lectura, preferiblemente con otro equipo, y revisar la calidad del soplo.", marker: { kind: "point", gas: "h2", time: 75 } },
  { id: "sibo-a1", difficulty: 3, category: "SIBO", type: "SIBO • H₂", claim: "Un H₂ bajo durante todo el examen excluye completamente SIBO y cierra la investigación.", answer: false, t: [0, 15, 30, 45, 60, 75, 90, 120], h2: [1, 1, 2, 1, 2, 2, 1, 2], ch4: [2, 2, 2, 2, 3, 3, 3, 4], meta: ["Lactulosa", "H₂ persistentemente bajo", "Sin elevación colónica"], short: "Posible no respondedor al H₂", why: "El material describe a los no respondedores de H₂ y orienta a realizar la prueba con CH₄.", detail: "Una curva plana no debe interpretarse automáticamente como exclusión definitiva cuando hay sospecha de no producción de H₂.", marker: { kind: "flat", gas: "h2" } },
  { id: "sibo-a2", difficulty: 3, category: "SIBO", type: "SIBO • H₂", claim: "Un pico a los 120 min puede usarse como evidencia principal de SIBO cuando no hubo elevación antes de los 90 min.", answer: false, t: [0, 15, 30, 45, 60, 75, 90, 120], h2: [5, 6, 7, 8, 10, 12, 13, 46], ch4: [2, 2, 2, 2, 3, 3, 3, 4], meta: ["Lactulosa", "Pico tardío: 120 min", "Sin síntomas"], short: "Pico tardío fuera de la ventana", why: "La elevación solo a los 120 min puede reflejar fermentación colónica.", detail: "La ventana temporal es parte del criterio y evita confundir la fermentación colónica con SIBO.", marker: { kind: "time", time: 90 } },
  { id: "imo-a1", difficulty: 3, category: "IMO", type: "IMO • CH₄", claim: "Un H₂ bajo con CH₄ de 33 ppm a los 120 min puede indicar IMO incluso con SIBO negativo.", answer: true, t: [0, 15, 30, 45, 60, 75, 90, 120], h2: [2, 3, 3, 4, 4, 5, 5, 6], ch4: [4, 6, 8, 11, 16, 22, 28, 33], meta: ["Lactulosa", "CH₄: 33 ppm a los 120 min", "Distensión sin diarrea"], short: "CH₄ elevado con H₂ bajo", why: "El material presenta exactamente este patrón: SIBO negativo por H₂ e IMO positivo por CH₄.", detail: "La lectura conjunta de los gases evita perder el diagnóstico de IMO en pacientes con H₂ bajo.", marker: { kind: "threshold", gas: "ch4", value: 10 } },
  { id: "lac-a1", difficulty: 3, category: "Lactose", type: "Lactosa • H₂", claim: "Diarrea y flatulencia intensas, con H₂ sin elevación, confirman intolerancia a la lactosa.", answer: false, t: [0, 30, 60, 90, 120, 150, 180], h2: [1, 2, 2, 3, 4, 5, 6], ch4: [2, 2, 2, 2, 3, 3, 3], meta: ["Lactosa", "H₂ sin elevación", "Diarrea + flatulencia"], short: "Síntomas sin criterio gasométrico", why: "Los síntomas aislados no confirman intolerancia según la prueba; el material considera la posibilidad de no respondedor y sugiere repetir con CH₄.", detail: "Es un escenario de posible falso negativo del H₂.", marker: { kind: "flat", gas: "h2" } },
  { id: "fru-a1", difficulty: 3, category: "Frutose", type: "Fructosa • H₂", claim: "Una prueba de fructosa debe interpretarse hasta los 180 minutos, y no cerrarse a los 90 minutos.", answer: true, t: [0, 30, 60, 90, 120, 150, 180], h2: [3, 4, 6, 8, 15, 26, 34], ch4: [2, 2, 2, 2, 3, 3, 4], meta: ["Fructosa", "Elevación después de 120 min", "Sin síntomas"], short: "Monitorización hasta los 180 min", why: "El material describe lecturas cada 30 minutos hasta los 180 minutos para fructosa.", detail: "Cerrar a los 90 min puede perder elevaciones relevantes en pruebas de carbohidratos.", marker: { kind: "time", time: 180 } },
  { id: "sac-a1", difficulty: 3, category: "Sacarose", type: "Sacarosa • H₂", claim: "Si la primera lectura basal está registrada incorrectamente, el umbral del gráfico también quedará incorrecto.", answer: true, t: [0, 30, 60, 90, 120, 150, 180], h2: [10, 12, 15, 22, 31, 38, 42], ch4: [2, 2, 2, 3, 3, 3, 4], meta: ["Sacarosa", "Basal: 10 ppm", "Sin síntomas"], short: "El basal define el umbral", why: "El material muestra un ejemplo de error gráfico causado por posicionar incorrectamente la primera lectura.", detail: "La interpretación depende de la variación en relación con el basal.", marker: { kind: "point", gas: "h2", time: 0 } },
  { id: "qual-a1", difficulty: 3, category: "Qualidade", type: "Calidad del examen", claim: "Lecturas persistentemente en cero pueden representar un no respondedor al H₂ o un problema de calibración.", answer: true, t: [0, 15, 30, 45, 60, 75, 90, 120], h2: [0, 0, 0, 0, 0, 0, 0, 0], ch4: [2, 2, 2, 2, 2, 2, 2, 2], meta: ["Prueba de H₂", "Todas las lecturas: 0", "Revisar equipo/paciente"], short: "Curva totalmente en cero", why: "El material cita el error de calibración o el no respondedor al H₂ como posibilidades.", detail: "La orientación es evaluar el equipo y, en el contexto de no respondedor, considerar la prueba H₂–CH₄.", marker: { kind: "flat", gas: "h2" } },
  { id: "qual-e1", difficulty: 4, category: "Qualidade", type: "Calidad del examen", claim: "El vómito durante el examen puede justificar la suspensión y reprogramación por riesgo de falso negativo.", answer: true, t: [0, 15, 30, 45, 60, 75, 90, 120], h2: [4, 5, 7, 9, 10, 11, 12, 13], ch4: [2, 2, 2, 3, 3, 3, 4, 4], meta: ["Monitorización", "Vómito después del sustrato", "Riesgo de pérdida del sustrato"], short: "El vómito compromete el examen", why: "El material orienta a suspender y reprogramar porque el sustrato puede haberse eliminado, llevando a un falso negativo.", detail: "Aquí el punto central no es la curva, sino la validez preanalítica de la monitorización.", marker: { kind: "time", time: 45 } },
  { id: "qual-e2", difficulty: 4, category: "Qualidade", type: "Calidad del examen", claim: "El tabaquismo durante el estudio puede elevar el H₂ y generar un falso positivo.", answer: true, t: [0, 15, 30, 45, 60, 75, 90, 120], h2: [4, 5, 7, 18, 30, 38, 42, 48], ch4: [2, 2, 2, 3, 3, 4, 4, 5], meta: ["Calidad", "Paciente fumó durante la prueba", "Factor de confusión"], short: "El tabaquismo altera el H₂", why: "El material cita el tabaco como causa de falso positivo y alteración de las concentraciones de H₂.", detail: "El caso entrena el reconocimiento de un interferente antes de interpretar el gráfico.", marker: { kind: "time", time: 45 } },
  { id: "qual-e3", difficulty: 4, category: "Qualidade", type: "Calidad del examen", claim: "Dormir durante la prueba puede aumentar el H₂ por hipoventilación y producir un falso positivo.", answer: true, t: [0, 15, 30, 45, 60, 75, 90, 120], h2: [5, 6, 8, 12, 25, 31, 35, 39], ch4: [2, 2, 2, 3, 3, 3, 4, 4], meta: ["Calidad", "Paciente durmió", "Hipoventilación"], short: "Sueño durante el examen", why: "El material incluye dormir durante el examen como posible causa de falso positivo por hipoventilación.", detail: "El entrenamiento debe separar el patrón gasométrico de la interferencia técnica/comportamental.", marker: { kind: "time", time: 60 } },
  { id: "qual-e4", difficulty: 4, category: "Qualidade", type: "Calidad del examen", claim: "Un soplo corto o débil puede contribuir a un falso negativo en ancianos, asmáticos y niños.", answer: true, t: [0, 15, 30, 45, 60, 75, 90, 120], h2: [3, 3, 4, 4, 5, 5, 6, 6], ch4: [2, 2, 2, 2, 3, 3, 3, 3], meta: ["Calidad", "Soplo corto/débil", "Paciente anciano"], short: "Recolección espiratoria inadecuada", why: "El material relaciona un soplo incorrecto con falsos negativos, especialmente en ancianos, asmáticos y niños.", detail: "Antes de concluir negatividad, debe verificarse la calidad de la recolección.", marker: { kind: "flat", gas: "h2" } },
  { id: "sibo-e1", difficulty: 4, category: "SIBO", type: "SIBO • H₂", claim: "En un caso con SIBO previamente positivo, la prueba de intolerancia a la fructosa debe interpretarse con cautela por riesgo de falso positivo.", answer: true, t: [0, 30, 60, 90, 120, 150, 180], h2: [5, 12, 24, 36, 48, 55, 60], ch4: [2, 2, 3, 3, 4, 4, 5], meta: ["Fructosa después de SIBO positivo", "Curva precoz", "Riesgo de falso positivo"], short: "SIBO puede confundir la prueba de carbohidratos", why: "El material orienta a realizar primero la prueba de SIBO, ya que un SIBO positivo puede generar falsos positivos en las pruebas de intolerancia.", detail: "Este es un caso de integración entre la secuencia diagnóstica y la interpretación del gráfico.", marker: { kind: "time", time: 90 } },
  { id: "lac-e1", difficulty: 4, category: "Lactose", type: "Lactosa • H₂/CH₄", claim: "H₂ y CH₄ bajos hasta los 180 minutos, a pesar de la diarrea, todavía no comprueban intolerancia a la lactosa.", answer: true, t: [0, 30, 60, 90, 120, 150, 180], h2: [3, 4, 5, 5, 6, 7, 7], ch4: [2, 2, 3, 3, 4, 4, 4], meta: ["Lactosa", "H₂/CH₄ sin elevación", "Diarrea"], short: "Síntomas sin elevación en ambos gases", why: "El material presenta un escenario similar y discute la posibilidad de otro perfil, sin confirmar la intolerancia mediante la prueba.", detail: "La enseñanza aquí es resistir la tentación de convertir un síntoma aislado en un resultado positivo.", marker: { kind: "flat", gas: "h2" } },
  { id: "fru-e1", difficulty: 4, category: "Frutose", type: "Fructosa • H₂", claim: "En la prueba de fructosa, los síntomas deben considerarse en la clasificación entre malabsorción e intolerancia.", answer: true, t: [0, 30, 60, 90, 120, 150, 180], h2: [4, 6, 9, 13, 27, 35, 38], ch4: [2, 2, 2, 3, 3, 3, 4], meta: ["Fructosa", "H₂ +34 ppm", "Dolor + distensión"], short: "Curva positiva + síntomas", why: "El material incorporó la presencia de síntomas en la clasificación de intolerancia a carbohidratos.", detail: "El gráfico define la malabsorción; la asociación con síntomas sustenta la clasificación de intolerancia en el material.", marker: { kind: "delta", gas: "h2", base: 4, value: 24 } },
];

export function casesFor(lang: "pt" | "es"): RespiratoryCase[] {
  return lang === "es" ? respiratoryCasesEs : respiratoryCasesPt;
}
